### ISSUE TITLE
první úkol je odevzdaný

### ISSUE THREAD

**Issue by MAATOVAA** [MAATOVAA/PYTHON_PROGRAMOVANI#1]
@Cattitude

**Comment by cattitude** [comment]
@MAATOVAA 
Ahoj, super, všechno tady vidím. Opravím a dám vědět:)

Adam

**Comment by cattitude** [comment]
Ahoj @MAATOVAA,

díval jsem se na tvůj úkol, konkrétně na verzi s bonusy, a vypadá moc dobře.:) Skvělá práce, úkol máš splněný.:)

Zde je pár drobností, kterých jsem si všiml:
- Šla by do abstraktní třídy Property přidat ještě jedna abstraktní metoda, která pak máš u obou tříd Estate i Residence?:)
- Líbí se mi použití slovníku pro koeficienty pozemku. Teoreticky bys ještě mohla ošetřit stav, kdy uživatel zadá neplatný typ pozemku - buď nějakou podmínkou nebo třeba výchozí hodnotou v metodě get. 
- Při inicializaci objektu třídy TaxReport by možná stačilo výchozí hodnotu property_list nastavit rovnou na prázdný seznam [] a mohla by ses zbavit podmínky. 
- U metod __str__ by si šlo víc pohrát se samotným výpisem, aby v něm bylo více informací, zobrazovaly se české názvy (místo True a False) apod. Nicméně to už je drobnost.

Jestli s tím chceš ještě pohrát, to nechám na tobě. Každopádně kdyby ses rozhodla ještě udělat commit, klidně mě pak zase označ a můžu na to mrknout.:)

Měj se
Adam

**Comment by MAATOVAA** [comment]
Pěkný večer Adame,
odevzdala jsem druhý úkol, část první, druhou a bonus.
Velice děkuji za podporu, Alice

**Comment by cattitude** [comment]
Ahoj @MAATOVAA,

potvrzuji, že úkol vidím. Mrknu na něj a dám vědět.

Adam

**Comment by cattitude** [comment]
Ahoj @MAATOVAA,

díval jsem se na tvůj úkol a vypadá fajn, vše funguje a žádné zásadní prohřešky jsem nenašel, máš tedy splněno.:)

Pár drobných poznámek:
- U první části importuješ knihovnu json, ale pak ji nepoužíváš, bylo by tedy fajn ji z kódu odstranit (VS Code ti ji v tomto případě i zobrazí méně výraznou barvou).
-  Ve funkci pro vyhledání právní formy z číselníku je ta `else: continue` větev nadbytečná, protože python bude v cyklu automaticky pokračovat, pokud nebude splněna podmínka.
- Při používání konkrétních indexů v seznamu nebo klíčů ve slovníku by se ti mohlo stát, že nebudou existovat. To by šlo podchytit například `try: ... except: ...` blokem, který jsme si nedávno ukazovali. Nicméně na tohle úkol zaměřený nebyl, takže to ber opravdu jen jako náměť, jak to třeba posunout dál.:) 
- Doporučuji taky kód naformátovat třeba pomocí rozšíření black, které jsme si kdysi ukazovali, vypadá to pak líp a člověk to nemusí dělat manuálně.:)

Gratuluji k dobře odvedené práci a přeji hezký víkend.:)
Adam

**Comment by MAATOVAA** [comment]
Děkuji Ti Adame, odeslala jsem lepší verzi 2.úkolu.
